import LevelDefaultIcon from '@/components/ui/icons/live-stream/leveldefaultIcon'
import type { LevelListItemData } from './level.types'

export const LEVEL_COLORS = {
	background: {
		main: '#0A1121',
		gradientEnd: '#102038',
	},
	text: {
		primary: '#FFFFFF',
		secondary: '#A9A9A9',
		tertiary: '#808080',
	},
	header: {
		bar: 'rgba(10, 17, 33, 0.95)',
		tabActiveUnderline: '#ADD8E6',
		tabInactive: '#A0A0A0',
	},
	purple: {
		primary: '#5F22D9',
		badgeStart: '#7E30E6',
		badgeEnd: '#A05FFF',
	},
	button: {
		rechargeStart: '#7E30E6',
		rechargeEnd: '#00C8FF',
	},
	orange: {
		badge: '#FF8C00',
	},
	badge: {
		level0Bg: '#2C2C2C',
		level0Icon: '#3D168B',
		defaultBg: '#3D168B',
	},
	card: {
		background: '#1A1A1A',
		userCardGlow: 'rgba(126, 48, 230, 0.15)',
	},
} as const

export const LEVEL_LAYOUT = {
	headerHeight: 56,
	tabsHeight: 44,
	horizontalPadding: 20,
	cardBorderRadius: 16,
	listItemBorderRadius: 12,
	avatarSize: 60,
	gemIconSize: 115,
	progressBarHeight: 6,
	badgeHeight: 28,
	listItemGap: 10,
} as const

export const RICH_LEVEL_LIST_DATA: LevelListItemData[] = [
	{
		levelLabel: 'Level 0',
		coinRange: '0 - 5k Coins',
		badgeNumber: '0',
		badgeVariant: 'level0',
		badgeIcon: LevelDefaultIcon,
	},
	{
		levelLabel: 'Level 1-5',
		coinRange: '5 - 85.2k Coins',
		badgeNumber: '5',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/1-10.png'),
	},
	{
		levelLabel: 'Level 6-10',
		coinRange: '85.2k - 348.8k Coins',
		badgeNumber: '10',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/1-10.png'),
	},
	{
		levelLabel: 'Level 11-15',
		coinRange: '348.8k - 783.8k Coins',
		badgeNumber: '15',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/10-20.png'),
	},
	{
		levelLabel: 'Level 16-20',
		coinRange: '783.8k - 1.39M Coins',
		badgeNumber: '20',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/10-20.png'),
	},
	{
		levelLabel: 'Level 21-25',
		coinRange: '1.39M - 2.17M Coins',
		badgeNumber: '25',
		badgeVariant: 'orange',
		badgeIcon: require('@/assets/diamonds-levels/20-25.png'),
	},
	{
		levelLabel: 'Level 26-30',
		coinRange: '2.17M - 3.13M Coins',
		badgeNumber: '30',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/25-30.png'),
	},
	{
		levelLabel: 'Level 31-35',
		coinRange: '3.13M - 4.35M Coins',
		badgeNumber: '35',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/25-30.png'),
	},
	{
		levelLabel: 'Level 36-40',
		coinRange: '4.35M - 5.87M Coins',
		badgeNumber: '40',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/35-40.png'),
	},
	{
		levelLabel: 'Level 41-45',
		coinRange: '5.87M - 7.71M Coins',
		badgeNumber: '45',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/35-40.png'),
	},
	{
		levelLabel: 'Level 46-50',
		coinRange: '7.71M - 9.89M Coins',
		badgeNumber: '50',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/45-50.png'),
	},
	{
		levelLabel: 'Level 51-55',
		coinRange: '9.89M - 12.4M Coins',
		badgeNumber: '55',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/45-50.png'),
	},
	{
		levelLabel: 'Level 56-60',
		coinRange: '12.4M - 15.4M Coins',
		badgeNumber: '60',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/55-60.png'),
	},
	{
		levelLabel: 'Level 61-65',
		coinRange: '15.4M - 18.8M Coins',
		badgeNumber: '65',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/55-60.png'),
	},
	{
		levelLabel: 'Level 66-70',
		coinRange: '18.8M - 22.7M Coins',
		badgeNumber: '70',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/65-70.png'),
	},
	{
		levelLabel: 'Level 71-75',
		coinRange: '22.7M - 27.1M Coins',
		badgeNumber: '75',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/65-70.png'),
	},
	{
		levelLabel: 'Level 76-80',
		coinRange: '27.1M - 32.1M Coins',
		badgeNumber: '80',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/75-80.png'),
	},
	{
		levelLabel: 'Level 81-85',
		coinRange: '32.1M - 37.7M Coins',
		badgeNumber: '85',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/75-80.png'),
	},
	{
		levelLabel: 'Level 86-90',
		coinRange: '37.7M - 43.9M Coins',
		badgeNumber: '90',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/80-85.png'),
	},
	{
		levelLabel: 'Level 91-95',
		coinRange: '43.9M - 50.8M Coins',
		badgeNumber: '95',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/80-85.png'),
	},
	{
		levelLabel: 'Level 96-100',
		coinRange: '50.8M - 58.3M Coins',
		badgeNumber: '100',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/90-100.png'),
	},
	{
		levelLabel: 'Super level',
		coinRange: '58.3M+ Coins',
		badgeNumber: '100',
		badgeVariant: 'default',
		badgeIcon: require('@/assets/diamonds-levels/90-100.png'),
	},
]

export const CHARM_LEVEL_LIST_DATA: LevelListItemData[] = [
	{
		levelLabel: 'Level 0',
		coinRange: '0 - 5k Coins',
		badgeNumber: '0',
		badgeVariant: 'level0',
	},
	{
		levelLabel: 'Level 1-5',
		coinRange: '5 - 85.2k Coins',
		badgeNumber: '5',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 6-10',
		coinRange: '85.2k - 348.8k Coins',
		badgeNumber: '10',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 11-15',
		coinRange: '348.8k - 783.8k Coins',
		badgeNumber: '15',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 16-20',
		coinRange: '783.8k - 1.39M Coins',
		badgeNumber: '20',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 21-25',
		coinRange: '1.39M - 2.17M Coins',
		badgeNumber: '25',
		badgeVariant: 'orange',
	},
	{
		levelLabel: 'Level 26-30',
		coinRange: '2.17M - 3.13M Coins',
		badgeNumber: '30',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 31-35',
		coinRange: '3.13M - 4.35M Coins',
		badgeNumber: '35',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 36-40',
		coinRange: '4.35M - 5.87M Coins',
		badgeNumber: '40',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 41-45',
		coinRange: '5.87M - 7.71M Coins',
		badgeNumber: '45',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 46-50',
		coinRange: '7.71M - 9.89M Coins',
		badgeNumber: '50',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 51-55',
		coinRange: '9.89M - 12.4M Coins',
		badgeNumber: '55',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 56-60',
		coinRange: '12.4M - 15.4M Coins',
		badgeNumber: '60',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 61-65',
		coinRange: '15.4M - 18.8M Coins',
		badgeNumber: '65',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 66-70',
		coinRange: '18.8M - 22.7M Coins',
		badgeNumber: '70',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 71-75',
		coinRange: '22.7M - 27.1M Coins',
		badgeNumber: '75',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 76-80',
		coinRange: '27.1M - 32.1M Coins',
		badgeNumber: '80',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 81-85',
		coinRange: '32.1M - 37.7M Coins',
		badgeNumber: '85',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 86-90',
		coinRange: '37.7M - 43.9M Coins',
		badgeNumber: '90',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 91-95',
		coinRange: '43.9M - 50.8M Coins',
		badgeNumber: '95',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Level 96-100',
		coinRange: '50.8M - 58.3M Coins',
		badgeNumber: '100',
		badgeVariant: 'default',
	},
	{
		levelLabel: 'Super level',
		coinRange: '58.3M+ Coins',
		badgeNumber: '100',
		badgeVariant: 'default',
	},
]
