import { Dimensions } from 'react-native'

const { width: SCREEN_WIDTH } = Dimensions.get('window')

export const AGENT_DASHBOARD = {
	SCREEN_WIDTH,
	screenPadding: 16,
	sectionGap: 20,
	cardBorderRadius: 16,
	cardBg: '#fff',
	cardShadowColor: '#000',
	cardPadding: 16,
	labelColor: '#666666',
	valueColor: '#1A1A1A',
	headerGradientStart: '#6A62F0',
	headerGradientEnd: '#C0BDF3',
	headerTextColor: '#FFFFFF',
	tabSelectedBg: '#fff',
	tabUnselectedText: '#666666',
	tabSelectedText: '#000',
	sectionTitleColor: '#1A1A1A',
	toolCardBorderRadius: 10,
	toolCardAddHostBg: '#E3F2FD',
	toolCardInviteAgentBg: '#F3E5F5',
	toolCardCoinTradingBg: '#FFF3E0',
	toolCardRankingBg: '#E8F5E9',
	toolCardRewardBg: '#FCE4EC',
	bannerBg: '#6A62F0',
	bannerTextColor: '#FFFFFF',
	bannerRibbonBg: 'rgba(255,255,255,0.25)',
	withdrawButtonHeight: 36,
	withdrawButtonPaddingHorizontal: 14,
	withdrawButtonBorderRadius: 18,
	withdrawButtonBackground: '#3495FF',
	withdrawButtonFontSize: 14,
	withdrawButtonFontWeight: '600' as const,
	withdrawButtonTextColor: '#FFFFFF',
	dividerColor: '#E0E0E0',
	progressBarHeight: 6,
	progressBarBg: '#FF2D55',
	progressBarFill: '#FF2D55',
	progressMarkerBg: '#FF2D55',
	progressMarkerText: '#000000',
	earningRequiresColor: '#6A62F0',
	progressRingPurple: '#5F22D9',
	promoRowBorderColor: '#EEEEEE',
	promoTagOriginalBg: '#E8E0F0',
	promoTagBeginnerBg: '#D3F7DD',
	promoTagOriginalText: '#5E35B1',
	promoTagBeginnerText: '#22D956',
	dataSubNavUnderline: '#5F22D9',
	dataRefreshText: '#999999',
	dataGridGap: 12,
	dataChartLine: '#5F22D9',
	dataChartGrid: '#E0E0E0',
	dataChartDot: '#5F22D9',
	hostAnalysisTotalCardBg: '#F5E4E9',
	hostAnalysisManageButtonBorder: '#FF383C',
	hostAnalysisManageButtonText: '#FF383C',
	hostAnalysisGradeButtonBg: '#E9E9E9',
	hostAnalysisGradeButtonActiveBg: '#D0D0D0',
	hostAnalysisDonutBlue: '#87CEEB',
	hostAnalysisDonutPink: '#F4A0A8',
	hostAnalysisDonutPurple: '#9B7DD9',
	hostAnalysisDailyCardBg: '#FFFFFF',
	hostAnalysisDailyCardSelectedBg: '#E9E9E9',
	hostAnalysisCardShadow: 'rgba(0,0,0,0.06)',
	incomeOverviewCardSelectedBg: '#E9E9E9',
	incomeCompositionProgressPink: '#FF2D55',
	incomeCompositionProgressBlue: '#3495FF',
	incomeCompositionProgressTrack: '#E9E9E9',
	addHostFilterPurple: '#5F22D9',
	addHostRowBg: '#F0F9F0',
	addHostTagBg: '#5F22D9',
	addHostWageEmptyBg: '#B3E0F7',
	addHostSearchBg: '#E9E9E9',
} as const
