export const MANAGE = {
	cardBorderRadius: 20,
	cardPadding: 20,
	gridGap: 16,
	shadowColor: '#000',
	shadowOffset: { width: 0, height: 2 },
	shadowOpacity: 0.06,
	shadowRadius: 8,
	elevation: 3,
	accentColor: '#E65100',
	accentBorderColor: '#F26721',
	numberColor: '#F26721',
	labelColor: '#1A1A1A',
	iconBgLightBlue: '#E4F1FD',
	iconBgLightYellow: '#FEF3C7',
	iconBgLightPink: '#FCE7F3',
	iconBgLightPurple: '#EDE7F9',
	iconBorderRadius: 14,
} as const
