export const LIVE_DATA = {
	screenBg: '#FFFFFF',
	cardBg: '#F8F6FB',
	cardBorderRadius: 20,
	datePickerBg: '#fff',
	buttonBg: '#6B46C1',
	buttonText: '#FFFFFF',
	activeColor: '#000000',
	inactiveColor: '#A0A0A0',
	valueColor: '#1A1A1A',
	labelColor: '#1A1A1A',
	screenPadding: 16,
	cardPadding: 20,
	mainTabUnderlineHeight: 3,
	subTabUnderlineHeight: 2,
	weeklyScreenBg: '#F0F0F0',
	weeklyCardBg: '#FFFFFF',
	weeklyCardBorderRadius: 12,
	weeklyCardShadow: 'rgba(0,0,0,0.06)',
	weeklyDividerColor: '#E5E5E5',
	chartPointsColor: '#B22A2A',
	chartDurationColor: '#007AFF',
	chartDotStrokeWidth: 2,
	earningsIconInner: '#FF9500',
	earningsIconOuter: '#FF6B4A',
	pkCardWinGradient: ['#D4A84B', '#C99A3A', '#B8862E'] as const,
	pkCardScoreGradient: ['#E84C7A', '#D63D6A', '#C22E5A'] as const,
	pkCardSessionsGradient: ['#4A9EED', '#3A8DD9', '#2E7BC2'] as const,
} as const
